### ISSUE TITLE
NullPointerException encountered in LFXNetworkSettings

### ISSUE THREAD

**Issue by iheart2code** [besherman/lifx-sdk-java#26]
Here is the stack trace. Unfortunately, I don't have steps to reproduce at this time.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List java.net.NetworkInterface.getInterfaceAddresses()' on a null object reference
       at com.github.besherman.lifx.impl.network.LFXNetworkSettings.getFirstActiveBroadcast(LFXNetworkSettings.java:64)
       at com.github.besherman.lifx.impl.network.LFXNetworkSettings.getBroadcast(LFXNetworkSettings.java:55)
       at com.github.besherman.lifx.impl.network.LFXMessageRouter.sendBroadcast(LFXMessageRouter.java:291)
       at com.github.besherman.lifx.impl.network.LFXMessageRouter.access$000(LFXMessageRouter.java:52)
       at com.github.besherman.lifx.impl.network.LFXMessageRouter$4.run(LFXMessageRouter.java:360)
       at com.github.besherman.lifx.impl.network.LFXTimerQueue$TimerTaskImpl.run(LFXTimerQueue.java:97)
       at java.util.Timer$TimerImpl.run(Timer.java:284)
```

**Comment by iheart2code** [comment]
OK, I have found out how to reproduce this.
1. Instantiate a LFXClient
2. Set group & light listeners on the client
3. Open the client with `LFXClient.open(false);`
4. Wait for the devices to start getting discovered
5. Turn off Wi-Fi

**Comment by iheart2code** [comment]
I was apparently retrying the open command after wi-fi loss. Should probably throw an exception in LFXClient.open if there is no connected network interfaces. I'd submit a PR for this, but I'm not sure what is the most platform-agnostic way about doing that. I'm developing for Android.

**Comment by besherman** [comment]
Ah, tricky. Hopefully I'll have time to check this out tomorrow.

**Comment by iheart2code** [comment]
I think that #30 was a duplicate of this one.
