### ISSUE TITLE
SocketException: Permission denied

### ISSUE THREAD

**Issue by joakimar** [besherman/lifx-sdk-java#27]
I'm running my application as root. It works intermittently, but spews out a lot of this error message.

I'm confused that this error can be intermittent. "permission denied" is usually pretty permanent. Maybe the error is really something else, like a full buffer of some sort?

2015-01-28 16:17:22 SEVERE com.github.besherman.lifx.impl.network.LFXNetworkLoopConnection$Writer run Failed to send message
java.net.SocketException: Permission denied
	at sun.nio.ch.DatagramChannelImpl.send0(Native Method)
	at sun.nio.ch.DatagramChannelImpl.sendFromNativeBuffer(DatagramChannelImpl.java:532)
	at sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:509)
	at sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:473)
	at com.github.besherman.lifx.impl.network.LFXNetworkLoopConnection$Writer.run(LFXNetworkLoopConnection.java:157)
	at java.lang.Thread.run(Thread.java:745)

**Comment by iheart2code** [comment]
Are you running the version of the project that is up on Maven Central?

**Comment by joakimar** [comment]
Yup!

**Comment by joakimar** [comment]
I tried using the version from HEAD, and your fix to the Datagram sockets worked! Thanks.

**Comment by magicmass** [comment]
How did this get resolved? I'm having the same issue and there is no advice on how to resolve it. Is anyone able to help?
@loefberg 
@iheart2code
