### ISSUE TITLE
No lights detected (and tests show message/parsing problem and problem finding gateway)

### ISSUE THREAD

**Issue by boddeke** [besherman/lifx-sdk-java#35]
hello,
i have 8 lifx lights (firmware 2) and i cannot get this to work (macbook, jdk1.8.0_31, nb 8.0.2).
LightEx01PrintLights gives no lights. LightEx08PrintDetails shows a message/parsing problem and LightEx05CollectionListener says there is no gateway?
let me know if i can run any other tests to help
thanks,
frank

LightEx01PrintLights gives no output at all

LightEx08PrintDetails gives:

Feb 20, 2015 10:08:07 AM com.github.besherman.lifx.impl.network.LFXNetworkLoopConnection$Reader run
SEVERE: Failed to parse message: 5C00005400000000D073D50087D600004C49465856320000846639C66E91C41338000000C06CB9AA3B124C588F59FA100A03BFCF00000000000000000000000000000000000000000000000000000000000000000000000000000000
java.lang.IllegalStateException: message data has type value=56 which is not in LxProtocol.typeMap
	at com.github.besherman.lifx.impl.entities.internal.LFXMessage.getTypeFromMessageData(LFXMessage.java:497)
	at com.github.besherman.lifx.impl.entities.internal.LFXMessage.<init>(LFXMessage.java:199)
	at com.github.besherman.lifx.impl.network.LFXNetworkLoopConnection$Reader.run(LFXNetworkLoopConnection.java:250)
	at java.lang.Thread.run(Thread.java:744)

LightEx05CollectionListener gives (about 1 minute running):

Feb 20, 2015 10:26:58 AM com.github.besherman.lifx.impl.network.LFXMessageRouter sendWithPath
SEVERE: No address for gateway, this should not happen
Feb 20, 2015 10:26:58 AM com.github.besherman.lifx.impl.network.LFXMessageRouter sendWithPath
SEVERE: No address for gateway, this should not happen
Feb 20, 2015 10:26:58 AM com.github.besherman.lifx.impl.network.LFXMessageRouter sendWithPath
SEVERE: No address for gateway, this should not happen
Feb 20, 2015 10:26:58 AM com.github.besherman.lifx.impl.network.LFXMessageRouter sendWithPath
SEVERE: No address for gateway, this should not happen
Feb 20, 2015 10:26:58 AM com.github.besherman.lifx.impl.network.LFXMessageRouter sendWithPath
SEVERE: No address for gateway, this should not happen
Feb 20, 2015 10:26:58 AM com.github.besherman.lifx.impl.network.LFXMessageRouter sendWithPath
SEVERE: No address for gateway, this should not happen
Feb 20, 2015 10:26:58 AM com.github.besherman.lifx.impl.network.LFXMessageRouter sendWithPath
SEVERE: No address for gateway, this should not happen
Feb 20, 2015 10:26:58 AM com.github.besherman.lifx.impl.network.LFXMessageRouter sendWithPath
SEVERE: No address for gateway, this should not happen
Feb 20, 2015 10:26:58 AM com.github.besherman.lifx.impl.network.LFXMessageRouter sendWithPath
SEVERE: No address for gateway, this should not happen
Feb 20, 2015 10:26:58 AM com.github.besherman.lifx.impl.network.LFXMessageRouter sendWithPath
SEVERE: No address for gateway, this should not happen
Feb 20, 2015 10:26:58 AM com.github.besherman.lifx.impl.network.LFXMessageRouter sendWithPath
SEVERE: No address for gateway, this should not happen
Feb 20, 2015 10:26:58 AM com.github.besherman.lifx.impl.network.LFXMessageRouter sendWithPath
SEVERE: No address for gateway, this should not happen
Feb 20, 2015 10:26:58 AM com.github.besherman.lifx.impl.network.LFXMessageRouter sendWithPath
SEVERE: No address for gateway, this should not happen
Feb 20, 2015 10:26:58 AM com.github.besherman.lifx.impl.network.LFXMessageRouter sendWithPath
SEVERE: No address for gateway, this should not happen
Light added, label '' and id 'D073D500ED83' 
Feb 20, 2015 10:26:58 AM com.github.besherman.lifx.impl.network.LFXMessageRouter sendWithPath
SEVERE: No address for gateway, this should not happen
Feb 20, 2015 10:27:20 AM com.github.besherman.lifx.impl.network.LFXNetworkLoopConnection$Reader run
SEVERE: Failed to parse message: 6400005400000000D073D500A2AA00004C4946585632000044E5143A7B92C4133B0000004C494658FA73255E7B92C41300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
java.lang.IllegalStateException: message data has type value=59 which is not in LxProtocol.typeMap
	at com.github.besherman.lifx.impl.entities.internal.LFXMessage.getTypeFromMessageData(LFXMessage.java:497)
	at com.github.besherman.lifx.impl.entities.internal.LFXMessage.<init>(LFXMessage.java:199)
	at com.github.besherman.lifx.impl.network.LFXNetworkLoopConnection$Reader.run(LFXNetworkLoopConnection.java:250)
	at java.lang.Thread.run(Thread.java:744)

Feb 20, 2015 10:27:23 AM com.github.besherman.lifx.impl.network.LFXMessageRouter sendWithPath
SEVERE: No address for gateway, this should not happen
Feb 20, 2015 10:27:23 AM com.github.besherman.lifx.impl.network.LFXMessageRouter sendWithPath
SEVERE: No address for gateway, this should not happen
Feb 20, 2015 10:27:23 AM com.github.besherman.lifx.impl.network.LFXMessageRouter sendWithPath
SEVERE: No address for gateway, this should not happen
Feb 20, 2015 10:27:23 AM com.github.besherman.lifx.impl.network.LFXMessageRouter sendWithPath
SEVERE: No address for gateway, this should not happen
Feb 20, 2015 10:27:23 AM com.github.besherman.lifx.impl.network.LFXMessageRouter sendWithPath
SEVERE: No address for gateway, this should not happen
Feb 20, 2015 10:27:23 AM com.github.besherman.lifx.impl.network.LFXMessageRouter sendWithPath
SEVERE: No address for gateway, this should not happen
Feb 20, 2015 10:27:23 AM com.github.besherman.lifx.impl.network.LFXMessageRouter sendWithPath
SEVERE: No address for gateway, this should not happen
Feb 20, 2015 10:27:23 AM com.github.besherman.lifx.impl.network.LFXMessageRouter sendWithPath
SEVERE: No address for gateway, this should not happen
Feb 20, 2015 10:27:23 AM com.github.besherman.lifx.impl.network.LFXMessageRouter sendWithPath
SEVERE: No address for gateway, this should not happen
Feb 20, 2015 10:27:23 AM com.github.besherman.lifx.impl.network.LFXMessageRouter sendWithPath
SEVERE: No address for gateway, this should not happen
Feb 20, 2015 10:27:23 AM com.github.besherman.lifx.impl.network.LFXMessageRouter sendWithPath
SEVERE: No address for gateway, this should not happen
Feb 20, 2015 10:27:23 AM com.github.besherman.lifx.impl.network.LFXMessageRouter sendWithPath
SEVERE: No address for gateway, this should not happen
Light added, label 'Tafel kamer' and id 'D073D500A2AA' 
Feb 20, 2015 10:27:23 AM com.github.besherman.lifx.impl.network.LFXMessageRouter sendWithPath
SEVERE: No address for gateway, this should not happen
Feb 20, 2015 10:27:24 AM com.github.besherman.lifx.impl.network.LFXNetworkLoopConnection$Reader run
SEVERE: Failed to parse message: 5C00005400000000D073D500A2AA00004C4946585632000004CB70287C92C4133500000074037BC8CDF9356D323BA3664EB5F825546166656C000000000000000000000000000000000000000000000000000000001269C33006BF13
java.lang.IllegalStateException: message data has type value=53 which is not in LxProtocol.typeMap
	at com.github.besherman.lifx.impl.entities.internal.LFXMessage.getTypeFromMessageData(LFXMessage.java:497)
	at com.github.besherman.lifx.impl.entities.internal.LFXMessage.<init>(LFXMessage.java:199)
	at com.github.besherman.lifx.impl.network.LFXNetworkLoopConnection$Reader.run(LFXNetworkLoopConnection.java:250)
	at java.lang.Thread.run(Thread.java:744)

Feb 20, 2015 10:27:27 AM com.github.besherman.lifx.impl.network.LFXNetworkLoopConnection$Reader run
SEVERE: Failed to parse message: 5C00005400000000D073D500A2AA00004C49465856320000045FA69F7C92C41332000000E45BD2AD3F5A2DD6721A7599386E1012486F6D65000000000000000000000000000000000000000000000000000000000070ACA43006BF13
java.lang.IllegalStateException: message data has type value=50 which is not in LxProtocol.typeMap
	at com.github.besherman.lifx.impl.entities.internal.LFXMessage.getTypeFromMessageData(LFXMessage.java:497)
	at com.github.besherman.lifx.impl.entities.internal.LFXMessage.<init>(LFXMessage.java:199)
	at com.github.besherman.lifx.impl.network.LFXNetworkLoopConnection$Reader.run(LFXNetworkLoopConnection.java:250)
	at java.lang.Thread.run(Thread.java:744)

Feb 20, 2015 10:27:29 AM com.github.besherman.lifx.impl.network.LFXNetworkLoopConnection$Reader run
SEVERE: Failed to parse message: 5C00005400000000D073D500A2AA00004C4946585632000084E3D6197D92C41338000000C06CB9AA3B124C588F59FA100A03BFCF00000000000000000000000000000000000000000000000000000000000000000000000000000000
java.lang.IllegalStateException: message data has type value=56 which is not in LxProtocol.typeMap
	at com.github.besherman.lifx.impl.entities.internal.LFXMessage.getTypeFromMessageData(LFXMessage.java:497)
	at com.github.besherman.lifx.impl.entities.internal.LFXMessage.<init>(LFXMessage.java:199)
	at com.github.besherman.lifx.impl.network.LFXNetworkLoopConnection$Reader.run(LFXNetworkLoopConnection.java:250)
	at java.lang.Thread.run(Thread.java:744)

Feb 20, 2015 10:27:33 AM com.github.besherman.lifx.impl.network.LFXMessageRouter sendWithPath
SEVERE: No address for gateway, this should not happen
Feb 20, 2015 10:27:33 AM com.github.besherman.lifx.impl.network.LFXMessageRouter sendWithPath
SEVERE: No address for gateway, this should not happen
Light removed, label '' and id 'D073D500ED83' 
Feb 20, 2015 10:27:59 AM com.github.besherman.lifx.impl.network.LFXNetworkLoopConnection$Reader run
SEVERE: Failed to parse message: 6400005400000000D073D50087D600004C4946585632000044B4E64E8492C4133B0000004C4946583F7841528492C41300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
java.lang.IllegalStateException: message data has type value=59 which is not in LxProtocol.typeMap
	at com.github.besherman.lifx.impl.entities.internal.LFXMessage.getTypeFromMessageData(LFXMessage.java:497)
	at com.github.besherman.lifx.impl.entities.internal.LFXMessage.<init>(LFXMessage.java:199)
	at com.github.besherman.lifx.impl.network.LFXNetworkLoopConnection$Reader.run(LFXNetworkLoopConnection.java:250)
	at java.lang.Thread.run(Thread.java:744)

Feb 20, 2015 10:28:03 AM com.github.besherman.lifx.impl.network.LFXNetworkLoopConnection$Reader run
SEVERE: Failed to parse message: 5C00005400000000D073D50087D600004C49465856320000049A423D8592C41335000000571E5898B3B7662160DFC31361DE59574275726F0000000000000000000000000000000000000000000000000000000000676F2FB406BF13
java.lang.IllegalStateException: message data has type value=53 which is not in LxProtocol.typeMap
	at com.github.besherman.lifx.impl.entities.internal.LFXMessage.getTypeFromMessageData(LFXMessage.java:497)
	at com.github.besherman.lifx.impl.entities.internal.LFXMessage.<init>(LFXMessage.java:199)
	at com.github.besherman.lifx.impl.network.LFXNetworkLoopConnection$Reader.run(LFXNetworkLoopConnection.java:250)
	at java.lang.Thread.run(Thread.java:744)

Feb 20, 2015 10:28:05 AM com.github.besherman.lifx.impl.network.LFXNetworkLoopConnection$Reader run
SEVERE: Failed to parse message: 5C00005400000000D073D50087D600004C49465856320000841E73B78592C41332000000E45BD2AD3F5A2DD6721A7599386E1012486F6D65000000000000000000000000000000000000000000000000000000000065C62EB406BF13
java.lang.IllegalStateException: message data has type value=50 which is not in LxProtocol.typeMap
	at com.github.besherman.lifx.impl.entities.internal.LFXMessage.getTypeFromMessageData(LFXMessage.java:497)
	at com.github.besherman.lifx.impl.entities.internal.LFXMessage.<init>(LFXMessage.java:199)
	at com.github.besherman.lifx.impl.network.LFXNetworkLoopConnection$Reader.run(LFXNetworkLoopConnection.java:250)
	at java.lang.Thread.run(Thread.java:744)

Feb 20, 2015 10:28:07 AM com.github.besherman.lifx.impl.network.LFXNetworkLoopConnection$Reader run
SEVERE: Failed to parse message: 5C00005400000000D073D50087D600004C4946585632000084B2A82E8692C41338000000C06CB9AA3B124C588F59FA100A03BFCF00000000000000000000000000000000000000000000000000000000000000000000000000000000
java.lang.IllegalStateException: message data has type value=56 which is not in LxProtocol.typeMap
	at com.github.besherman.lifx.impl.entities.internal.LFXMessage.getTypeFromMessageData(LFXMessage.java:497)
	at com.github.besherman.lifx.impl.entities.internal.LFXMessage.<init>(LFXMessage.java:199)
	at com.github.besherman.lifx.impl.network.LFXNetworkLoopConnection$Reader.run(LFXNetworkLoopConnection.java:250)
	at java.lang.Thread.run(Thread.java:744)

Feb 20, 2015 10:28:09 AM com.github.besherman.lifx.impl.network.LFXMessageRouter sendWithPath
SEVERE: No address for gateway, this should not happen
Feb 20, 2015 10:28:09 AM com.github.besherman.lifx.impl.network.LFXMessageRouter sendWithPath
SEVERE: No address for gateway, this should not happen
Feb 20, 2015 10:28:09 AM com.github.besherman.lifx.impl.network.LFXMessageRouter sendWithPath
SEVERE: No address for gateway, this should not happen
Feb 20, 2015 10:28:09 AM com.github.besherman.lifx.impl.network.LFXMessageRouter sendWithPath
SEVERE: No address for gateway, this should not happen
Feb 20, 2015 10:28:09 AM com.github.besherman.lifx.impl.network.LFXMessageRouter sendWithPath
SEVERE: No address for gateway, this should not happen
Feb 20, 2015 10:28:09 AM com.github.besherman.lifx.impl.network.LFXMessageRouter sendWithPath
SEVERE: No address for gateway, this should not happen
Feb 20, 2015 10:28:09 AM com.github.besherman.lifx.impl.network.LFXMessageRouter sendWithPath
SEVERE: No address for gateway, this should not happen
Feb 20, 2015 10:28:09 AM com.github.besherman.lifx.impl.network.LFXMessageRouter sendWithPath
Light added, label '' and id 'D073D50087D6' 
SEVERE: No address for gateway, this should not happen
Feb 20, 2015 10:28:09 AM com.github.besherman.lifx.impl.network.LFXMessageRouter sendWithPath
SEVERE: No address for gateway, this should not happen
Feb 20, 2015 10:28:09 AM com.github.besherman.lifx.impl.network.LFXMessageRouter sendWithPath
SEVERE: No address for gateway, this should not happen
Feb 20, 2015 10:28:09 AM com.github.besherman.lifx.impl.network.LFXMessageRouter sendWithPath
SEVERE: No address for gateway, this should not happen
Feb 20, 2015 10:28:09 AM com.github.besherman.lifx.impl.network.LFXMessageRouter sendWithPath
SEVERE: No address for gateway, this should not happen
Feb 20, 2015 10:28:09 AM com.github.besherman.lifx.impl.network.LFXMessageRouter sendWithPath
SEVERE: No address for gateway, this should not happen
Feb 20, 2015 10:28:11 AM com.github.besherman.lifx.impl.network.LFXMessageRouter sendWithPath
SEVERE: No address for gateway, this should not happen
Feb 20, 2015 10:28:11 AM com.github.besherman.lifx.impl.network.LFXMessageRouter sendWithPath
SEVERE: No address for gateway, this should not happen
Light removed, label 'Tafel kamer' and id 'D073D500A2AA'

**Comment by besherman** [comment]
Yeah, firmware 2.0 really made life more interesting... What happens if you try the lifx-sdk-java 1.0.1 release?

**Comment by besherman** [comment]
The "message data has type value=53 which is not in LxProtocol.typeMap" message means that we are getting packages that are probably important but we don't know what they are. Since they haven't updated [LIFXkit](https://github.com/LIFX/LIFXKit) since the new firmware we have no way of finding out what they are.

**Comment by boddeke** [comment]
hi richard

	i tried and that works fine!

	do you want met to try other stuff to help debug this?

thanks,
frank
